apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python-app
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: app-container
          image: docker.io/urcloplop/python-app:0.0.1
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: "/obj"
          livenessProbe:
            tcpSocket:
              port: 80
          startupProbe:
            httpGet:
              port: 80
              path: "/obj"
